name: GeoVerity 2026 – Repo Protection & Validation

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: TypeScript strict mode
        run: npm run type-check

  beads-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Validate beads database
        run: npm run beads:validate

  localization-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Build site
        run: npm run build
      - name: Localization Parity Check
        run: node scripts/validate_localization.js

  accessibility-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Build site
        run: npm run build
      - name: Accessibility Scan
        run: node scripts/accessibility_scan.js

  governance-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Data Governance Scan
        run: node scripts/data_governance_scan.js

  lighthouse-mobile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Install Lighthouse
        run: npm install -g lighthouse
      - name: Build site
        run: npm run build
      - name: Start preview server
        run: npm run preview &
      - name: Wait for server
        run: npx wait-on http://localhost:4321
      - name: Lighthouse Mobile Performance
        run: bash scripts/lighthouse_ci.sh

  building-pages-review:
    runs-on: ubuntu-latest
    # Only run on pull requests
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for merge-base
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Get PR body
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (pr && pr.body) {
              core.exportVariable('PR_BODY', pr.body);
            } else {
              console.log('No pull_request payload or body found - review may come from file');
            }
      - name: Validate Building Pages Compliance Review
        run: node scripts/validate_building_pages_review.js
